/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ritcher;

import java.awt.BorderLayout;

import javax.swing.JPanel;

/**
 *
 * @author thiago
 */
public class AppFrame extends javax.swing.JFrame {
    
    private static final long serialVersionUID = 1L;
	private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AppFrame.class.getName());
	private Menu menu;
	private PanelFactory factory;

    /**
     * Creates new form AppFrame
     */
    public AppFrame(Menu menu, PanelFactory factory) {
    	this.factory = factory;
    	this.menu = menu;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        menubar = new javax.swing.JMenuBar();


        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        content.setLayout(new java.awt.BorderLayout());
        getContentPane().add(content, java.awt.BorderLayout.CENTER);
        
        menu.create().stream().forEach(m -> menubar.add(m));
        setJMenuBar(menubar);
       
        setupMenuSelectionListener();
        
        pack();
    }// </editor-fold>                        

    private void setupMenuSelectionListener() {
    	menu.addMenuListener(new MenuSelectionListener() {
			@Override
			public void selected(String id) {
				JPanel panel = factory.createPanel(id);
				content.removeAll();
				content.add(panel, BorderLayout.CENTER);
				pack();
			}
		});
	}

	/**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify                     
    public final javax.swing.JPanel content = new javax.swing.JPanel();
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JMenuBar menubar;
    // End of variables declaration                   
}
