/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ritcher.ui;

import java.awt.BorderLayout;
import java.awt.EventQueue;

import javax.swing.JPanel;

import br.com.ritcher.Content;
import br.com.ritcher.PanelFactory;

/**
 *
 * @author thiago
 */
public class AppFrame extends javax.swing.JFrame {
    
    private static final long serialVersionUID = 1L;
	private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AppFrame.class.getName());
	private final Menu menu;
	private final Content content;
	
	private final BottomPanel bottomPanel;

    /**
     * Creates new form AppFrame
     */
    public AppFrame(Content content, Menu menu, BottomPanel bottomPanel) {
    	this.content = content;
    	this.menu = menu;
		this.bottomPanel = bottomPanel; 
        initComponents();
        setSize(800, 600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        menubar = new javax.swing.JMenuBar();


        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        getContentPane().add(content, java.awt.BorderLayout.CENTER);
        
        menu.create().stream().forEach(m -> menubar.add(m));
        setJMenuBar(menubar);
       
        add(bottomPanel, BorderLayout.SOUTH);
        
       
        //pack();
    }// </editor-fold>                        

  

    // Variables declaration - do not modify                     
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JMenuBar menubar;
    // End of variables declaration                   
}
