/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.ritcher.ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JButton;
import javax.swing.event.HyperlinkEvent;
import javax.swing.event.HyperlinkListener;

/**
 *
 * @author thiago
 */
public class BottomPanel extends javax.swing.JPanel {

	private MessagesFrame messagesFrame;
	private MessageLinkFocusHandler focusHandler;
	/**
	 * Creates new form BottomPanel
	 */
	public BottomPanel(MessagesFrame messagesFrame, MessageLinkFocusHandler focusHandler) {
		this.messagesFrame = messagesFrame;
		this.focusHandler = focusHandler;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		jScrollPane2 = new javax.swing.JScrollPane();
		jEditorPane1 = new javax.swing.JEditorPane();
		jButton1 = new JButton();
		
		
		jEditorPane1.setEditable(false);
		jEditorPane1.setContentType("text/html");
		jEditorPane1.addHyperlinkListener(new HyperlinkListener() {
			@Override
			public void hyperlinkUpdate(HyperlinkEvent e) {
				jEditorPane1HyperlinkUpdate(e);
			}
		});


		setLayout(new java.awt.GridBagLayout());

		jScrollPane2.setViewportView(jEditorPane1);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.weighty = 1.0;
		add(jScrollPane2, gridBagConstraints);

		jButton1.setText("Log");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 0);
		add(jButton1, gridBagConstraints);
		
		jButton1.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				messagesFrame.setVisible(true);
			}
		});
		
		
		setMessage("<b color='red'>Erro</b> ao salvar <a href='http://Form/10/nome'>acessar</a>");

	}// </editor-fold>

	public void setMessage(String string) {
		jEditorPane1.setText("<html><body>"+string+"</body></html>");
	}
	
	 private void jEditorPane1HyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {                                             
		// TODO add your handling code here:
		HyperlinkEvent e = evt;
		if (e.getEventType() == HyperlinkEvent.EventType.ACTIVATED) {
			focusHandler.handleLink(e.getURL());
		}
	}                                            


	// Variables declaration - do not modify
    private javax.swing.JButton jButton1;
	private javax.swing.JEditorPane jEditorPane1;
	private javax.swing.JScrollPane jScrollPane2;
	// End of variables declaration
}
