/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ritcher.ui;

import javax.swing.event.HyperlinkEvent;

/**
 *
 * @author thiago
 */
public class MessagesFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MessagesFrame.class.getName());
	private MessageLinkFocusHandler linkFocusHandler;

    /**
     * Creates new form MessagesFrame
     */
    public MessagesFrame(MessageLinkFocusHandler linkFocusHandler) {
        this.linkFocusHandler = linkFocusHandler;
		initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        jEditorPane1.setEditable(false);
        jEditorPane1.setContentType("text/html"); // NOI18N
        jEditorPane1.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p>\n       Executando função de processamento de nota\n    </p>\n    <p>\n       <b color='red'>Problema de validação</b>, informação não disponível <a href=\"http://Form/10/nome \">acessar</a>\n    </p>\n  </body>\n</html>\n");
        jEditorPane1.addHyperlinkListener(new javax.swing.event.HyperlinkListener() {
            public void hyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {
                jEditorPane1HyperlinkUpdate(evt);
            }
        });
        jScrollPane1.setViewportView(jEditorPane1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>                        

    private void jEditorPane1HyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {                                             
        // TODO add your handling code here:
        HyperlinkEvent e = evt;
        if (e.getEventType() == HyperlinkEvent.EventType.ACTIVATED) {
        	linkFocusHandler.handleLink(e.getURL());
        }
    }                                            

    // Variables declaration - do not modify                     
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration                   
}
