/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.ritcher.ui;

import java.awt.Component;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import javax.swing.JTabbedPane;

import br.com.ritcher.Content;
import br.com.ritcher.ContentData;
import br.com.ritcher.UI;

/**
 *
 * @author thiago
 */
public class SplitPane extends javax.swing.JPanel implements Content {

    private static final ContentData NO_DATA = new ContentData("Dados");
	/**
     * Creates new form SplitPane
     */
    public SplitPane() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        //jSplitPane1 = new javax.swing.JSplitPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        //jTabbedPane2 = new javax.swing.JTabbedPane();

        setLayout(new java.awt.BorderLayout());
        //jSplitPane1.setLeftComponent(jTabbedPane1);
        //jSplitPane1.setRightComponent(jTabbedPane2);
        add(jTabbedPane1, java.awt.BorderLayout.CENTER);
        //jSplitPane1.setDividerLocation(0);
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration                   

    
	@Override
	public void push(UI panel, ContentData data) {
		if(data == null) {
			data = NO_DATA;
		}
		jTabbedPane1.addTab(data.getName(), (Component) panel);
		jTabbedPane1.setSelectedIndex(jTabbedPane1.getTabCount() - 1);
	}

	@Override
	public void pop(UI panel) {
		int index = -1;
		if(panel != null) {
			index = jTabbedPane1.indexOfComponent((Component) panel);
		}
		else {
			index = jTabbedPane1.getTabCount() - 1;
		}

		if(index > -1)
			jTabbedPane1.removeTabAt(index);
	}


}
