/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.ritcher.ui;

import java.awt.Container;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.util.Iterator;
import java.util.List;

import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

import br.com.ritcher.model.Form;
import br.com.ritcher.model.FormItem;
import br.com.ritcher.model.Input;
import br.com.ritcher.model.Line;
import br.com.ritcher.model.input.TextLine;

/**
 *
 * @author thiago
 */
public class UIForm extends javax.swing.JPanel {

    private Form form;
	/**
     * Creates new form NewJPanel1
     * @param form 
     */
    public UIForm(Form form) {
    	this.form = form;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        setLayout(new java.awt.GridBagLayout());
        
        List<FormItem> itens = form.getFormItems();
        Integer y = -1;

        for (FormItem formItem : itens) {
        	y++;
			if(formItem instanceof Line) {
				this.createLine((Line) formItem, this, y);
			}
			
			if(formItem instanceof Input) {
				this.createInput((Input) formItem, this, y);
			}
		}

    	GridBagConstraints gridBagConstraints;
		JLabel label = new JLabel();
		label.setText("");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridy = y + 1;
		gridBagConstraints.weighty = 1.0;
		gridBagConstraints.fill = GridBagConstraints.REMAINDER;
		

		add(label, gridBagConstraints);

    }// </editor-fold>//GEN-END:initComponents

    private void createInput(Input input, Container container, Integer y) {
    	GridBagConstraints gridBagConstraints;

		JLabel label = new JLabel();
		label.setText(input.getLabel());
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
		gridBagConstraints.gridy = y;
		gridBagConstraints.anchor = GridBagConstraints.EAST;
		container.add(label, gridBagConstraints);

		JTextField textField = new JTextField();
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.gridy = y;
		gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
		container.add(textField, gridBagConstraints);
	}


	private void createLine(Line line, Container container, Integer y) {

    	JPanel linePanel = new JPanel();
    	linePanel.setLayout(new GridBagLayout());
    	
        List<Input> itens = line.getInputs();
        for (Input formItem : itens) {
			if(formItem instanceof Input) {
				this.createInput(formItem, linePanel, 0);
			}
		}

    	GridBagConstraints gridBagConstraints;
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.gridy = y;
		gridBagConstraints.gridwidth = 2;
		gridBagConstraints.weightx = 1.0;

        
        container.add(linePanel, gridBagConstraints);
	}

}
