/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.ritcher.ui;

import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.ActionEvent;
import java.text.DateFormat;
import java.text.NumberFormat;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Timer;
import java.util.TimerTask;

import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;

import br.com.ritcher.Content;
import br.com.ritcher.UI;
import br.com.ritcher.impl.model.SearchItemImpl;
import br.com.ritcher.model.Form;
import br.com.ritcher.model.FormItem;
import br.com.ritcher.model.Input;
import br.com.ritcher.model.Line;
import br.com.ritcher.model.input.DateInput;
import br.com.ritcher.model.input.IntegerInput;
import br.com.ritcher.model.input.SearchItem;
import br.com.ritcher.model.input.SelectItem;
import br.com.ritcher.model.input.Switch;
import br.com.ritcher.model.input.TextLine;
import br.com.ritcher.ui.search.SearchInput;
import br.com.ritcher.ui.search.SearchProvider;

/**
 *
 * @author thiago
 */
public class UIForm extends javax.swing.JPanel implements UI, FormActionListener{

    private Form form;
	private SearchProvider provider;
	
	private Map<String, JComponent> componentById = new HashMap<String, JComponent>();
	private final FormActionPanel actionPanel;
	
	/**
     * Creates new form NewJPanel1
     * @param form 
     */
    public UIForm(Form form, SearchProvider provider, FormActionPanel actionPanel) {
    	this.form = form;
		this.provider = provider;
		this.actionPanel = actionPanel;
		actionPanel.initComponents(this);
        initComponents();
    }
    
    
    
    private Content getContent() {
    	Component c = getParent();
    	while(!(c instanceof Content)) {
    		c = c.getParent();
    	}
    	return (Content) c;
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        setLayout(new java.awt.GridBagLayout());
        
    	GridBagConstraints gridBagConstraints;

        
        List<FormItem> itens = form.getFormItems();
        Integer y = 0;

        Integer max = 0; 
        for (FormItem formItem : itens) {
			if(formItem instanceof Line) {
				max = Integer.max(max, this.countInputs((Line) formItem));
			}
		}
        
        
		gridBagConstraints = new java.awt.GridBagConstraints();
		
		gridBagConstraints.gridx = 0;
		gridBagConstraints.anchor = GridBagConstraints.WEST;
		gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.gridwidth = max;
		
        add(actionPanel, gridBagConstraints);
        
        
        for (FormItem formItem : itens) {
        	y += 2;
			if(formItem instanceof Line) {
				this.createLine((Line) formItem, this, y, max);
			}
			
			if(formItem instanceof Input) {
				this.createInput((Input) formItem, this, 0,  y, max);
			}
		}

		JLabel label = new JLabel();
		label.setText("");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridy = y + 3;
		gridBagConstraints.weighty = 1.0;
		gridBagConstraints.fill = GridBagConstraints.REMAINDER;
		

		add(label, gridBagConstraints);

    }// </editor-fold>//GEN-END:initComponents

    private int countInputs(Line formItem) {
    	return formItem.getInputs().size();
	}
    
    Component first;

	private void createInput(Input input, Container container,  Integer x, Integer y, Integer width) {
    	GridBagConstraints gridBagConstraints;
    	
    	Integer inputW = width;
    	Integer labelW = width;
    	
    	Integer inputY = y + 1;
    	Integer labelY = y;

    	Integer inputX = x;
    	Integer labelX = x;
   
    	
		JComponent textField = createComponent(input);
		componentById.put(input.getLabel(), textField);
		textField.requestFocusInWindow();
		
		if(first == null) {
			first = textField;
			textField.requestFocusInWindow();
		}
		
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.gridy = inputY;
		gridBagConstraints.gridx = inputX;
		gridBagConstraints.gridwidth = inputW;
		gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
		container.add(textField, gridBagConstraints);
    	
    	if(!(input instanceof Switch)) {
			JLabel label = new JLabel();
			label.setText(input.getLabel());
			gridBagConstraints = new java.awt.GridBagConstraints();
			gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
			gridBagConstraints.gridy = labelY;
			gridBagConstraints.gridx = labelX;
			gridBagConstraints.gridwidth = labelW;
			
			gridBagConstraints.anchor = GridBagConstraints.WEST;

			container.add(label, gridBagConstraints);
			label.setLabelFor(textField);
    	}
	}


	private JComponent createComponent(Input input) {
		if(input instanceof TextLine) {
			return new JTextField();
		}
		if(input instanceof IntegerInput) {
			JFormattedTextField comp = new JFormattedTextField(NumberFormat.getIntegerInstance());
			return comp;
		}
		if(input instanceof DateInput) {
			JFormattedTextField comp = new JFormattedTextField(DateFormat.getDateInstance(DateFormat.SHORT));
			return comp;
		}
		if(input instanceof SelectItem) {
			JComboBox<String> comp = new JComboBox<String>();
			return comp;
		}
		if(input instanceof SearchItem) {
			SearchInput comp = new SearchInput((SearchItem) input, provider); 
			return comp;
		}
		if(input instanceof Switch) {
			JCheckBox comp = new JCheckBox();
			comp.setText(input.getLabel());
			return comp;
		}
		throw new IllegalArgumentException("Undefined input type" + input);
	}

	Color errorColor = new Color(255,102,102);
	
	public void focusPath(List<String> path) {
		String id = path.get(0);
		JComponent component = componentById.get(id);
		if(component != null) {
			component.requestFocusInWindow();
			Color original = component.getBackground();
			component.setBackground(errorColor);
			component.setToolTipText("Validation error");
			new Timer().schedule(new TimerTask() {
				@Override
				public void run() {
					SwingUtilities.invokeLater(new Runnable() {
						@Override
						public void run() {
							component.setBackground(original);
						}
					});
				}
			}, 3000);
		}
	}

	private void createLine(Line line, Container container, Integer y,  Integer width) {
        List<Input> itens = line.getInputs();
        int itemW = width / line.getInputs().size();
        int lastW = itemW + (width - line.getInputs().size() * itemW);
        int x = 0;
        Input lastItem = itens.get(0);
        for (Input formItem : itens) {
			if(formItem instanceof Input) {
				int w = lastItem == formItem ? lastW : itemW;
				this.createInput(formItem, this,x, y, w);
				x += w;
			}
		}
	}

	public void load(List<String> path) {
		String id = path.get(0);
		//Implement data loading
		SwingUtilities.invokeLater(new Runnable() {
			@Override
			public void run() {
				if(path.size() > 1) {
					focusPath(path.subList(1, path.size()));
				}
			}
		});
	}

	@Override
	public void salvarAction(ActionEvent e) {
		
	}

	@Override
	public void cancelarAction(ActionEvent e) {
		getContent().pop(this);
	}

	@Override
	public void fecharAction(ActionEvent e) {
		getContent().pop(this);
	}
}
