package br.com.ritcher.ui;

import java.awt.Color;
import java.awt.Component;
import java.awt.GridBagConstraints;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;

import javax.swing.AbstractCellEditor;
import javax.swing.BorderFactory;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.border.Border;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableCellRenderer;

import br.com.ritcher.model.Input;
import br.com.ritcher.model.Table;
import br.com.ritcher.model.input.Switch;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author thiago
 */
public class UITable extends javax.swing.JPanel {

	private static final long serialVersionUID = 1L;

	private Table item;

	private CreateComponent createComponent;

	private UXConfig uxConfig;

	/**
	 * Creates new form Table
	 */
	public UITable(Table item, CreateComponent createComponent, UXConfig uxConfig) {
		this.item = item;
		this.createComponent = createComponent;
		this.uxConfig = uxConfig;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jTextField2 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();

		setLayout(new java.awt.BorderLayout());

		dataModel = new UITableModel(item);
		jPanel1.setLayout(new java.awt.GridBagLayout());

		/*
		for (Input input : item.getInputs()) {
			if (!(input instanceof Switch)) {
				JLabel label = new JLabel();
				label.setText(input.getLabel());
				gridBagConstraints = new java.awt.GridBagConstraints();
				gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 0);
				jPanel1.add(label, gridBagConstraints);
			}

			JComponent component = createComponent.create(input);

			gridBagConstraints = new java.awt.GridBagConstraints();
			gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
			if (!(input instanceof Switch)) {
				gridBagConstraints.weightx = 1.0;
			}
			gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 0);
			jPanel1.add(component, gridBagConstraints);
		}
		*/
		
		jButton1.setText("+");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 0);
		gridBagConstraints.anchor = GridBagConstraints.EAST;
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.gridwidth = 1;

		
		jPanel1.add(jButton1, gridBagConstraints);
		jButton1.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				dataModel.addRow();
			}
		});

		jButton2.setText("-");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
		jPanel1.add(jButton2, gridBagConstraints);
		jButton2.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				dataModel.removeRow(jTable1, jTable1.getSelectedRow());
			}
		});

		add(jPanel1, java.awt.BorderLayout.NORTH);
		//jPanel1.setBackground(Color.black);

		jTable1.setModel(dataModel);
		jScrollPane1.setViewportView(jTable1);

		UICellEditorTextLine cellEditor = new UICellEditorTextLine(item, createComponent, uxConfig);
		CustomCellRenderer cellRenderer = new CustomCellRenderer(item, createComponent, uxConfig);
		
		jTable1.setCellEditor(cellEditor);
		for (int i = 0; i < item.getInputs().size(); i++) {
			jTable1.getColumnModel().getColumn(i).setCellEditor(cellEditor);
			jTable1.getColumnModel().getColumn(i).setCellRenderer(cellRenderer);
		}
		jTable1.setRowSelectionAllowed(true);

		add(jScrollPane1, java.awt.BorderLayout.CENTER);
	}// </editor-fold>

	class CustomCellRenderer implements TableCellRenderer {
		private JTextField label;
		private List<JComponent> editors;
		private CreateComponent createComponent;
		private UXConfig uxConfig;

		public CustomCellRenderer(Table table, CreateComponent createComponent, UXConfig uxConfig) {
			this.uxConfig = uxConfig;
			editors = table.getInputs().stream().map(i -> createComponent.create(i)).toList();
			this.createComponent = createComponent;
			label = new JTextField();
			label.setBorder(BorderFactory.createEmptyBorder());
	        //label.setOpaque(true);
		}

		@Override
		public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus,
				int row, int column) {
		
			if(isSelected) {
				label.setBackground(uxConfig.getPrimarySelection());
			}
			else {
				label.setBackground(Color.white);
			}
			if(value == null) {
				label.setText("");
			}
			else if(value instanceof String) {
				label.setText((String) value);
			}
			else {
				JComponent editor = editors.get(column);
				createComponent.setValue(editor, value);
				label.setText(createComponent.getText(editor));
			}
			return label;
		}
	}

	class UICellEditorTextLine extends AbstractCellEditor implements TableCellEditor {

		private static final long serialVersionUID = 1L;

		private Table table;

		private List<JComponent> editors;

		private CreateComponent createComponent;

		private int lastRow;

		private int lastcolumn;

		private JComponent currentEditor;

		private UXConfig uxConfig;
		
		public List<JComponent> getEditors() {
			return editors;
		}

		public UICellEditorTextLine(Table table, CreateComponent createComponent, UXConfig uxConfig) {
			this.table = table;
			this.createComponent = createComponent;
			this.uxConfig = uxConfig;
			editors = table.getInputs().stream().map(i -> createComponent.create(i)).toList();
		}

		@Override
		public Object getCellEditorValue() {
			return createComponent.getValue(currentEditor);
		}

		@Override
		public Component getTableCellEditorComponent(JTable table, Object value, boolean isSelected, int row,
				int column) {
			lastRow = row;
			lastcolumn = column;
			currentEditor = editors.get(column);
			createComponent.setValue(currentEditor, value);
			table.setRowHeight(row, (int) currentEditor.getPreferredSize().getHeight() + 5);
			currentEditor.setBackground(uxConfig.getPrimarySelection());
			return currentEditor;
		}
	}

	class UITableModel extends AbstractTableModel {

		private List<Object[]> values;

		private static final long serialVersionUID = 1L;
		private Table table;
		

		public UITableModel(Table table) {
			this.table = table;
			this.values = new ArrayList<Object[]>();
			addRow();
		}

		public void removeRow(JTable table, int i) {
			if(values.size() < 2) return;
			if(table.isEditing()) {
				table.getCellEditor().cancelCellEditing();
			}
			
			this.values.remove(i);
			fireTableRowsDeleted(i, i);
		}

		@Override
		public int getColumnCount() {
			return item.getInputs().size();
		}

		@Override
		public String getColumnName(int column) {
			return item.getInputs().get(column).getLabel();
		}
		
		public void addRow(){
			Object[] line = new Object[table.getInputs().size()];
			this.values.add(line);
			fireTableRowsInserted(this.values.size()-1, this.values.size());
		}

		@Override
		public int getRowCount() {
			return this.values.size();
		}

		@Override
		public boolean isCellEditable(int rowIndex, int columnIndex) {
			return true;
		}

		@Override
		public Object getValueAt(int rowIndex, int columnIndex) {
			if(rowIndex >= values.size()) return null;
			return values.get(rowIndex)[columnIndex];
		}

		public void setValueAt(Object value, int rowIndex, int columnIndex) {
			if(rowIndex >= values.size()) return;
			values.get(rowIndex)[columnIndex] = value;
		}
	}

	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	// End of variables declaration

	private UITableModel dataModel;
}
